version: "3.6"
services:
  goservice:
    build: "./service"
    ports:
      - "9000"
  nginx:
    build: "./nginx"
    ports:
      - "80:80"
    depends_on:
      - "goservice"
    links:
      - goservice:goservice
networks:
  web:
    driver: bridge